In [1]:
using LinearAlgebra

In [8]:
#
# Método da potência, para calcular o maior autovalor
# de uma matriz A de dimensão n × n com tolerância δ
#
function Metodo_Potencia(A,n,δ)
    
    # Inicializa o autovetor
    x = ones(n)
    
    # Inicializa o autovalor
    λ = 0.0
    
    # Inicializa o intervalo (para convergência)
    Δ = 1.0
    
    # Contador de iterações
    cont = 0
    
    # Loop enquanto o intervalo for maior do que a tolerância
    while Δ > δ
        
        # Estimativa do autovetor
        xk = A*x
        
        # Estivativa do autovalor
        λ_k = norm(xk)/norm(x)
        
        # Novo intervalo
        Δ = abs(λ_k - λ)
        
        # Copia a estimativa do autovetor para x
        x .= xk
        
        # Calcula a norma de x
        nx = norm(x)
        
        # Normaliza a estimativa do autovetor 
        x .= (1/nx)*x
        
        # Atualiza a estimativa do autovalor
        λ = λ_k
        
        # Atualiza o contador de iterações
        cont += 1
    end
    
    println("Convergência com tolerância $Δ em $cont iterações")
    
    # Retorna o maior autovalor e seu autovetor
    return λ, x
end

Metodo_Potencia (generic function with 1 method)

In [5]:
# Vamos definir uma matriz 3 × 3 para testar
A = [3   1.0  -0.5;
     1.0 5.0  -0.3
    -0.5 -0.3  4.0]

3×3 Matrix{Float64}:
  3.0   1.0  -0.5
  1.0   5.0  -0.3
 -0.5  -0.3   4.0

In [6]:
# Vamos utilizar o método do Julia para termos uma referência
eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 2.5011351012663177
 3.940078996598496
 5.558785902135194
vectors:
3×3 Matrix{Float64}:
  0.911497  -0.106641  -0.397242
 -0.336342   0.362651  -0.869113
  0.236743   0.925803   0.294688

In [9]:
# Agora usando o método da potência
Metodo_Potencia(A,3,1E-5)

Convergência com tolerância 8.425880493767579e-6 em 19 iterações


(5.558777394873301, [0.39705409058500196, 0.8697494399621349, -0.2930596540557394])