In [10]:
using LinearAlgebra

In [11]:
#
# Método da potência inversa, para calcular o menor autovalor
# de uma matriz A de dimensão n × n com tolerância δ
#

function  Metodo_Potencia_Inversa(A,n,δ)
    
    # Inicializa o autovetor
    x = ones(n)
    
    # Inicializa o autovalor
    λ = 0.0
    
    # Inicializa o intervalo (para convergência)
    Δ = 1.0
    
    # Contador de iterações
    cont = 0
    
    # Vamos fazer a decomposição LU da matriz A
    LU = lu(A)
    
    # Loop enquanto o intervalo for maior do que a tolerância
    while Δ > δ
  
        # Estimativa do autovetor - solução do sistema de equações
        xk = LU\x
        
        # Estimativa do autovalor
        λ_k = norm(x)/norm(xk)
        
        # Estimativa do intervalo
        Δ = abs(λ_k - λ)
        
        # Copia a estimativa do autovetor para x
        x .= xk
        
        # Calcula a norma de x
        nx = norm(x)
        
        # Normaliza a estimativa de autovetor
        x .= (1/nx)*x
        
        # Atualiza a estimativa do autovalor
        λ = λ_k
        
        # Atualiza o contador de iterações
        cont += 1
        
    end
    
     println("Convergência com tolerância $Δ em $cont iterações")
    
    # Retorna o menor autovalor e seu autovetor
    return λ, x
    
end


Metodo_Potencia_Inversa (generic function with 1 method)

In [12]:
# Vamos definir uma matriz 3 × 3 para testar
A = [3   1.0  -0.5;
     1.0 5.0  -0.3
    -0.5 -0.3  4.0]

3×3 Matrix{Float64}:
  3.0   1.0  -0.5
  1.0   5.0  -0.3
 -0.5  -0.3   4.0

In [13]:
# Vamos utilizar o método do Julia para termos uma referência
eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 2.5011351012663177
 3.940078996598496
 5.558785902135194
vectors:
3×3 Matrix{Float64}:
  0.911497  -0.106641  -0.397242
 -0.336342   0.362651  -0.869113
  0.236743   0.925803   0.294688

In [14]:
# Agora usando o método da potência
Metodo_Potencia_Inversa(A,3,1E-5)

Convergência com tolerância 6.977614238401486e-6 em 15 iterações


(2.5011398102909, [0.9113287244193371, -0.3357572426994668, 0.23821635129242366])