In [1]:
using LinearAlgebra

In [2]:
#
# Rotina Cholesky:
# Entradas: A       : Matriz
#           n       : Dimensao do sistema
# Saidas:   A       : U
#
#
function Cholesky!(A,n)
    #
    # Decompoe a matriz A usando Cholesky
    #
    for i=1:n
        for j=i:n
            
            # Realiza o somatorio
            soma = A[i,j]
            
            for k=1:i-1 
                soma = soma - A[k,i]*A[k,j]
            end #k

            # Verifica se estamos na diagonal
            if j==i 
                A[i,j] = sqrt(soma)
            else
                A[i,j] = soma / A[i,i]
            end
            
        end #j
    end #i

end

Cholesky! (generic function with 1 method)

In [3]:
A = 1.0*[2  1  1 ;
         1  8  1 ;
         1  1 10 ]

3×3 Matrix{Float64}:
 2.0  1.0   1.0
 1.0  8.0   1.0
 1.0  1.0  10.0

In [4]:
Cholesky!(A,3)

In [5]:
A

3×3 Matrix{Float64}:
 1.41421  0.707107  0.707107
 1.0      2.73861   0.182574
 1.0      1.0       3.07679

In [6]:
#
# Rotina Soluciona_por_Cholesky:
# Entradas: A       : Matriz simetrica e positivo definida
#           b       : vetor
#           n       : Dimensao do sistema
# Saidas:   b       : solucao do sistema
#
# Depende: Cholesky!(A,n)
#          zeros(n)
#
function Soluciona_por_Cholesky!(A,b,n)

    # Decompoe a matriz A em U'U
    Cholesky!(A,n)

    # Soluciona para y
    y = zeros(n)
    for i=1:n
        soma = 0.0
        for k=1:i-1
            soma = soma + A[k,i]*y[k]
        end #k
        y[i] = ( b[i] - soma ) / A[i,i]
    end #i

    # Soluciona para x (sobre b)
    for i=n:-1:1
        soma = 0.0
        for k=i+1:n
            soma = soma + A[i,k]*b[k]
        end #k
        b[i] = (y[i] - soma) / A[i,i]
    end #i
end

Soluciona_por_Cholesky! (generic function with 1 method)

In [11]:
A = 1.0*[2  1  1 ;
         1  8  1 ;
         1  1 10 ]

3×3 Matrix{Float64}:
 2.0  1.0   1.0
 1.0  8.0   1.0
 1.0  1.0  10.0

In [12]:
b = [1.0;2.0;3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [13]:
referencia = A\b

3-element Vector{Float64}:
 0.28169014084507044
 0.18309859154929578
 0.2535211267605634

In [14]:
Soluciona_por_Cholesky!(A,b,3)

In [10]:
b

3-element Vector{Float64}:
 0.2816901408450704
 0.18309859154929578
 0.25352112676056343