In [15]:
using LinearAlgebra

In [26]:
function Gauss_Seidel(A,x,b,n,tol,nmaxiter)
    xp = zeros(n)
    for k=0:nmaxiter
        norma = 0.0
        for i=1:n
            somatorio = 0.0
            for j=1:i-1
                somatorio = somatorio + A[i,j]*xp[j]
            end
            for j=i+1:n
                somatorio = somatorio + A[i,j]*x[j]
            end
            xp[i] = (1.0/A[i,i])*(b[i]-somatorio)
            norma = norma + (x[i]-xp[i])^2
        end
        if sqrt(norma) <= tol 
            println("Norma foi atingida ",norma," iteração ",k)
            break
        end
        # Copia xp para x
        x .= xp
    end #k
end

Gauss_Seidel (generic function with 1 method)

In [27]:
A = 1.0*[10 1 1 ; 2 7 0 ; 1 1 8]

3×3 Matrix{Float64}:
 10.0  1.0  1.0
  2.0  7.0  0.0
  1.0  1.0  8.0

In [28]:
b = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [29]:
A\b

3-element Vector{Float64}:
 0.07792207792207792
 0.12059369202226347
 0.10018552875695734

In [30]:
x = ones(3)
Gauss_Seidel(A,x,b,3,1E-5,10000)

Norma foi atingida 8.88623289934919e-11 iteração 4


In [31]:
x

3-element Vector{Float64}:
 0.0779126953125
 0.12059637276785713
 0.10018636648995535