In [1]:
using LinearAlgebra

In [2]:
#
# Rotina LU!:
#
# Entradas: A       : Matriz
#           n       : Dimensao do sistema
#
# Saidas:   A       : LU
#
#
function LU!(A,n)
    #
    # Decompoe a matriz A em LU
    #
    for i=1:n
        for j=1:n
            
            # Verifica se estamos abaixo ou acima da
            # diagonal principal
            if j<i 
                c = j
            else
                c = i
            end
            
            # Calcula o somatorio
            soma = A[i,j]
            for k=1:c-1
                soma = soma - A[i,k]*A[k,j]
            end #k
            
            # Armazena em A
            if j<=i 
                # L
                A[i,j] = soma
            else
                #U
                A[i,j] = soma / A[i,i]
            end
            
        end #j
    end #i
end

LU! (generic function with 1 method)

In [3]:
A = 1.0*[2  4  1 ;
         3  1 -1 ;
         1  1  1 ]

3×3 Matrix{Float64}:
 2.0  4.0   1.0
 3.0  1.0  -1.0
 1.0  1.0   1.0

In [4]:
LU!(A,3)

In [5]:
A

3×3 Matrix{Float64}:
 2.0   2.0  0.5
 3.0  -5.0  0.5
 1.0  -1.0  1.0

In [6]:
# Rotina Soluciona_por_LU:
#
# Entradas: A       : Matriz
#           b       : vetor
#           n       : Dimensao do sistema
# Saidas:   b       : solucao do sistema
#
# Depende: LU!(A,n)
# zeros(n)
#
function Soluciona_por_LU!(A,b,n)

    # Decompoe a matriz A em LU
    LU!(A,n)

    # Soluciona para y
    y = zeros(n)
    for i=1:n
        soma = 0.0
        for k=1:i-1 
            soma = soma + A[i,k]*y[k]
        end #k
        y[i] = ( b[i] - soma ) / A[i,i]
    end #i

    # Soluciona para x, armazenando em b
    for i=n:-1:1
        soma = 0.0
        for k=i+1:n
            soma = soma + A[i,k]*b[k]
        end #k
        b[i] = y[i] - soma
    end #i
    
end

Soluciona_por_LU! (generic function with 1 method)

In [7]:
A = 1.0*[2  4  1 ;
         3  1 -1 ;
         1  1  1 ]

3×3 Matrix{Float64}:
 2.0  4.0   1.0
 3.0  1.0  -1.0
 1.0  1.0   1.0

In [8]:
b = [1.0;2.0;3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [9]:
Soluciona_por_LU!(A,b,3)

In [10]:
b

3-element Vector{Float64}:
  1.9000000000000001
 -1.3
  2.4